import {renderTabs} from './tabs.js';
import {renderMenuButton} from './menu-button.js';
import {renderPlusMinusButton} from './plus-minus-button.js';
import {renderProduct} from './product.js';
import {renderCkeditor } from "./ckeditor.js";
import {renderFaqs } from "./faqs.js";
import {renderForm } from "./form.js";
import {renderProducts } from "./products.js";
import {renderSelect } from "./select.js";
import {renderSearchBar } from "./search-bar.js";
import {renderMenu} from './menu.js';
import {renderCart} from './cart.js';
import {renderCheckoutSuccessful} from './checkout-successful';
import {renderOrderPrice} from './order-price';

renderMenuButton();
renderTabs();
renderPlusMinusButton();
renderProduct();
renderCkeditor();
renderFaqs();
renderForm();
renderProducts();
renderSelect();
renderSearchBar();
renderCart();
renderMenu();
renderCheckoutSuccessful();
renderOrderPrice();